FORTUNES_LIST = [
  "Fate can be defined as small bits of enlightenment.", 
  "Somebody has gotta scare these hoes.",
  "It must be so nice to love you.",
  "My god does play dice.", 
  "Hard work is a prison only if it does not have meaning.", 
  "The best liar lies to themselves first.",
  "There is nothing to see except your fat ass.", 
  "At some point you deserve a beating.", 
  "Every rom-com has a happy ending.",
  "You can put your boots in the oven but that don't make 'em biscuits",  
  "Bake with the flour you've got.", 
  "You were not meant for the Cretaceous period.", 
  "The male equivalent of being treated as a sex object is being treated as a \"success object\".", 
  "Don't sacrifice your vision for anything.", 
  "If you can't imagine a universe where your dreams aren't real, you should imagine different universes.", 
  "There are no mistakes, only opportunities.", 
  "Your pelvis is going to get WHACKED tonight.", 
  "There is something wrong with you if you would, maybe, gulp an oyster.", 
  "How does it feel to be so wrong?", 
  "If the day comes to a close and you still want her head on your shoulder, let her wear her weird ass clothes.", 
  "Psychological warfare committed against men should never be leaked.",
  "You are the only person whose pants I would eat off of.", 
  "Have an ego-death experience later today.", 
  "If you're really that compatible, their cat shit wont smell that bad.", 
  "Place your values first, aptitude second, skills third.", 
  "You cant regulate people who have all the options.", 
  "You strike me as a creature who has control over every aspect of its life; quit being a pussy.", 
  "The lover inside of everyone is erratic.", 
  "There is always at least one ball in play... and sometimes two.",
  "Are you a mexi-can or a mexi-can't?.", 
  "You've gotta take some L's; this may be one of them.", 
  "The final product is a history of the piece's becoming.",
  "A big heart does not come with silence.",
  "Do not focus on results; ask yourself to dare greatly.",
  "Get your head out of your ass.", 
  "You can't outcompete someone who is living their dream.",
  "We have met the enemy and he is us.", 
  "You do not choose who you are, rather, you recognize yourself in its choosing of you.", 
  "The universe will flicker and dance while it reveals its plans for you.",
  "Don't believe in things you have to believe in.", 
  "A god ignored is a demon born.", 
  "You can't ride two horses with one ass.",
  "Creatures are very fond of proving their steadfast adherence to nonsense.", 
  "The only way out is through.",
  "Blood of the covenant is thicker than water of the womb",
  "Experience is what you get when you don't get what you wanted.",
  "You can shuffle a deck as many times as you want, but you're still playing with the same deck.",
  "Sometimes you have to climb a tree to see what's on the ground.",
  "Only boring people are bored",
  "Everything is best done in moderation; this goes for moderation as well.",
  "A new broom sweeps clean, but an old broom knows the corners",
  "Hunger is the best sauce",
  "They threw the pattern away when they made you.", 
  "Your eyes look like they followed the stars to meet me here. ",
  "It is better to lose because you played badly than because you didn’t understand the game. ",
  "There is no creature more powerful than a human who learns to love without fear.",
  "Where there is no chaos, there is no opportunity.",
  "Even a chicken knows when to get out of the rain", 
  "If you meet the Buddha on the road, you must kill him.", 
  "If you aint cheatin', you aint tryin.'", 
  "Growth begets complexity.", 
  "You're always between exploration and exploitation.",
  "Simplicity is the highest form of sophistication.",
  "Make sure your pants are zipped.", 
  "Make it easy and obvious for you, or the person you’re influencing, to do the desired behavior.", 
  "Sometimes it is possible to commit no errors and still fail. that is not weakness; that is life.",
  "Guilt is moral licensing so you can do it again.",
  "When you have eliminated the impossible, whatever remains must be the truth.", 
  "If you didn't know so much, you might learn something.", 
  "Preform a little trick and see if they love you yet.", 
  "My do it.", 
  "If you can't make her [explitive] with pleasure, at least make her [explitive] with joy.", 
  "Shit in one hand and wish in the other; see which fills up faster.",
  "Friction is a feature of intimacy.",
  "The answer to your question is always in graph form.",
  "You're not in the cuck chair for long.", 
  "Begin with the end in mind.", 
  "The best way to predict the future is to invent it", 
  "Work is love made visible.", 
  "If you've got a wonderful theory and the facts don't support it, your theory is wrong.", 
  "It seems like it is time to transcend.", 
  "Manipulation is not a prank", 
  "Start a list of clever names for indie bands.", 
  "Love, if it finds you worthy, directs your course.", 
  "Curiosity killed the cat, but satisfaction brought it back.",  
  "If you really want to be successful, get a big spoon because you're going to need to learn to eat a lot of shit",  
  ]